#pragma config(Sensor, port2,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port5,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port8,  bumpSwitchLeft, sensorVexIQ_Touch)
#pragma config(Sensor, port9,  bumpSwitchRight, sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will show how you can use a non-blocking command to perform other tasks while your
  motors are moving to a specific position. The motors will begin moving to position 5000, and
  while they're moving we'll display the current encoder value to the

                            ROBOT CONFIGURATION: VEX IQ Clawbot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                			[Location]
    Port 1        			leftMotor           VEX IQ Motor		      			Left side motor
    Port 6       				rightMotor          VEX IQ Motor		      			Right side motor (reversed)

------------------------------------------------------------------------------------------------*/

task main
{
  int ISeeColor;
  int ISeeObject;
	setColorMode(colorDetector, colorTypeRGB_Hue_Reflected);
	setDistanceMaxRange(distanceMM, 500);

	resetMotorEncoder(leftMotor);		//Reset the current position in the motor encoder to zero.
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(armMotor); //Take current position as zero.openLoop, encoder
	resetMotorEncoder(clawMotor);

  wait1Msec(50); //Small delay
	//setMotorSpeed(leftMotor, 50);
	//setMotorSpeed(rightMotor, 50);
	ISeeColor= getColorHue(colorDetector);
	ISeeObject = getDistanceValue(distanceMM);
	wait1Msec(50); //Small delay to allow motors time to start moving before checking

	//getMotorMoving - Flag to indiciate if the motor is moving (True - Moving / False - Stopped)
	//Loop while either motor is still moving (Left OR Right is still moving)
	//while(getMotorMoving(leftMotor) || getMotorMoving(rightMotor))
	//while ((ISeeColor < 60) || (ISeeColor > 120))
	while(ISeeObject > 70)
	{

		ISeeObject = getDistanceValue(distanceMM);
		//Print
		displayTextLine(1, "LM: %d, RM: %d", getMotorEncoder(leftMotor), getMotorEncoder(rightMotor));
		displayTextLine(2," Distance: %d",ISeeObject);
		sleep(10);
	}
	// Sees object, Stop motors

	// Stop motors
  setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	ISeeColor= getColorHue(colorDetector);
	displayTextLine(3," Hue:%d", ISeeColor);
	// if Green lift claw
	if ((ISeeColor > 60) && (ISeeColor < 120))
	  {
	  	setServoTarget(clawMotor, 90);
	  	sleep(500);
	    //Lift arm up and down
	    setServoTarget(armMotor, 300);  //Enable Servo Mode and move to position 60.
	    sleep(2000);
	    setServoTarget(armMotor, 10);   //Enable Servo Mode and move to position 10.
	    sleep(2000);
	    setServoTarget(clawMotor, 0);
	    sleep(2000);
//    } else {
	//if not, reverse for 1000 cycles
 //   	resetMotorEncoder(leftMotor);		//Reset the current position in the motor encoder to zero.
//	    resetMotorEncoder(rightMotor);
 //     moveMotorTarget(leftMotor, -500, -50);  //Set motor to run 5000 counts at power level 75.
//	    moveMotorTarget(rightMotor, -500, -50);
//	    waitUntilMotorStop(leftMotor);
//	    waitUntilMotorStop(rightMotor);
	  }
	}
