#pragma config(Sensor, port2,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port5,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port8,  bumpSwitchLeft, sensorVexIQ_Touch)
#pragma config(Sensor, port9,  bumpSwitchRight, sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program
  - searches for objects
  - approaches object
  - picks object up if green
  - else backs up and searches again.
------------------------------------------------------------------------------------------------*/

task main
{
  int ISeeColor;
  int ISeeObject;
	setColorMode(colorDetector, colorTypeRGB_Hue_Reflected);
	setDistanceMaxRange(distanceMM, 500);

	resetMotorEncoder(leftMotor);		//Reset the current position in the motor encoder to zero.
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(armMotor); //Take current position as zero.openLoop, encoder
	resetMotorEncoder(clawMotor);

  wait1Msec(50); //Small delay
  // rotate, looking for object





	ISeeColor= getColorHue(colorDetector);
	ISeeObject = getDistanceValue(distanceMM);
	// if sees something, move toward it.
	//setMotorSpeed(leftMotor, 50);
	//setMotorSpeed(rightMotor, -50);
  while(ISeeObject > 400)
	  {
      wait1Msec(500);
      ISeeObject = getDistanceValue(distanceMM);
      displayTextLine(1, "LM: %d, RM: %d", getMotorEncoder(leftMotor), getMotorEncoder(rightMotor));
		  displayTextLine(2," Distance: %d",ISeeObject);
	      // count rotations
	 }
	 // stop rotating when object detected

	// check that we are still moving toward object
	//   - stop
	//   - turn 10 degress left - take reading
	//   - turn 10 degress right - take reading       |
	//   - turn 10 degress right - take reading         /
	//  - turn and move towards greatest reading
	setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	wait1Msec(500); //Small delay to allow motors time to start moving before checking
//stopAllTasks();  // exut

	//getMotorMoving - Flag to indiciate if the motor is moving (True - Moving / False - Stopped)
	//Loop while either motor is still moving (Left OR Right is still moving)
	//while(getMotorMoving(leftMotor) || getMotorMoving(rightMotor))
	//while ((ISeeColor < 60) || (ISeeColor > 120))
	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 50);
	// while distance is decreasing - keep moving forward - if distance increases (lost target) stop and aquire target again
	while(ISeeObject > 85)
	{


		//Print
		displayTextLine(1, "LM: %d, RM: %d", getMotorEncoder(leftMotor), getMotorEncoder(rightMotor));
		displayTextLine(2," Distance: %d",ISeeObject);
		wait1Msec(5);
		ISeeObject = getDistanceValue(distanceMM);
	}
	// Sees object, Stop motors

	// Stop motors
  setMotorSpeed(leftMotor, 0);
	setMotorSpeed(rightMotor, 0);
	ISeeColor= getColorHue(colorDetector);
	displayTextLine(3," Hue:%d", ISeeColor);
	// if Green lift claw
	if ((ISeeColor > 60) && (ISeeColor < 120)) // if green and close
	  {
	  	// close claw
	  	setServoTarget(clawMotor, 110);
	  	sleep(500);
	    //Lift arm up and down
	    setServoTarget(armMotor, 300);  //Enable Servo Mode and move to position 60.
	    sleep(2000);
	    setServoTarget(armMotor, 10);   //Enable Servo Mode and move to position 10.
	    sleep(2000);
	    setServoTarget(clawMotor, 0);
	    sleep(2000);
    } else {
	//if not, reverse for 500 encoder units
    	resetMotorEncoder(leftMotor);		//Reset the current position in the motor encoder to zero.
	    resetMotorEncoder(rightMotor);
      moveMotorTarget(leftMotor, -500, -50);  //Set motor to run 5000 counts at power level 50
	    moveMotorTarget(rightMotor, -500, -50);
	    waitUntilMotorStop(leftMotor);
	    waitUntilMotorStop(rightMotor);
	  }
	}
